name: Push app to production link

on:
  workflow_call:
    inputs:
      server-flavour:
        description: "Server Flavour"
        required: true
        type: string
        default: "prod"

      company-name:
        description: "Company Name"
        required: false
        type: string

      prefix:
        description: "Prefix"
        required: true
        type: string
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: ./.github/actions/checkout-repos
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download apps from Google Drive
        uses: logickoder/google-drive-download@main
        with:
          authType: "oauth"
          clientId: ${{ secrets.OAUTH_CLIENT_ID }}
          clientSecret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          filename: "temp-${{ inputs.prefix }}-app-${{ inputs.company-name && format('{0}-', inputs.company-name) || '' }}${{ inputs.server-flavour }}-*.apk"
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
          destination: "./downloads/"

      - name: Rename artifacts
        env:
          ARTIFACT_PREFIX: ${{ inputs.prefix }}
        run: python3 -u releases/scripts/rename_artifacts.py "./downloads/" "$ARTIFACT_PREFIX" "temp-$ARTIFACT_PREFIX"

      - name: Upload apps to Google Drive
        uses: ./.github/actions/upload-to-drive
        with:
          filename: "./downloads/*.apk"
          mime-type: "application/vnd.android.package-archive"
          client-id: ${{ secrets.OAUTH_CLIENT_ID }}
          client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          folder-id: ${{ secrets.DRIVE_FOLDER_ID }}
