name: Push app to production link

on:
  workflow_call:
    inputs:
      server-flavour:
        description: "Server Flavour"
        required: true
        type: string
        default: "prod"

      company-name:
        description: "Company Name"
        required: false
        type: string

      prefix:
        description: "Prefix"
        required: true
        type: string
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repository
        uses: actions/checkout@v4
        with:
          repository: ptml-ng/releases
          path: releases
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download apps from Google Drive
        uses: logickoder/google-drive-download@main
        with:
          authType: "oauth"
          clientId: ${{ secrets.OAUTH_CLIENT_ID }}
          clientSecret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          filename: "temp-${{ inputs.prefix }}-app-${{ inputs.company-name && format('{0}-', inputs.company-name) || '' }}${{ inputs.server-flavour }}-*.apk"
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
          destination: "./downloads/"

      - name: Rename artifacts
        run: python3 -u releases/scripts/rename_artifacts.py "./downloads/" "${{ inputs.prefix }}" "temp-${{ inputs.prefix }}"

      - name: Upload apps to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          authType: "oauth"
          clientId: ${{ secrets.OAUTH_CLIENT_ID }}
          clientSecret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          filename: "./downloads/*.apk"
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
          overwrite: "true"
          mimeType: "application/vnd.android.package-archive"
